version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mju-bank-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mju_bank_db
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db_data:/var/lib/mysql #데이터가 사라지지 않게 로컬에 저장